export const data = {
	portList: {
		showall_param: [
			{
				slot_param: [],
				grid_param: [],
				traffic_param: [],
				name: 'eth0',
				real_name: 'eth0',
				status: 1,
				ip_address: '10.5.10.107/24',
				hw_addr: '00-10-f3-8e-98-bf',
				negotiate: 0,
				speed: 1000,
				half: 0,
				max_speed: 1000,
				rx_pkt: '28',
				rx_pkt_total: '17121244',
				send_pkt: '0',
				send_pkt_total: '69418',
				rx_byte: '14.000',
				rx_byte_total: '1129549050',
				send_byte: '0.000',
				send_byte_total: '32524454',
				bw_usage: 0,
				interface_type: 1,
				row_total: 0,
				col_total: 0,
				pattern: 0,
				need_syn: 0,
				enable: 0,
				ha_backup: 0,
				sessionid: '',
			},
			{
				slot_param: [],
				grid_param: [],
				traffic_param: [],
				name: 'eth1',
				real_name: 'eth1',
				status: 0,
				ip_address: '',
				hw_addr: '00-10-f3-8e-98-c0',
				negotiate: 0,
				speed: 0,
				half: 0,
				max_speed: 0,
				rx_pkt: '0',
				rx_pkt_total: '0',
				send_pkt: '0',
				send_pkt_total: '0',
				rx_byte: '',
				rx_byte_total: '0',
				send_byte: '',
				send_byte_total: '0',
				bw_usage: 0,
				interface_type: 2,
				row_total: 0,
				col_total: 0,
				pattern: 0,
				need_syn: 0,
				enable: 0,
				ha_backup: 0,
				sessionid: '',
			},
			{
				slot_param: [],
				grid_param: [],
				traffic_param: [],
				name: 'ge0/1',
				real_name: 'ge0/1',
				status: 0,
				ip_address: '',
				hw_addr: '00-10-f3-8e-98-c1',
				negotiate: 0,
				speed: 0,
				half: 0,
				max_speed: 0,
				rx_pkt: '0',
				rx_pkt_total: '0',
				send_pkt: '0',
				send_pkt_total: '0',
				rx_byte: '',
				rx_byte_total: '0',
				send_byte: '',
				send_byte_total: '0',
				bw_usage: 0,
				interface_type: 0,
				row_total: 0,
				col_total: 0,
				pattern: 0,
				need_syn: 0,
				enable: 0,
				ha_backup: 0,
				sessionid: '',
			},
			{
				slot_param: [],
				grid_param: [],
				traffic_param: [],
				name: 'ge0/2',
				real_name: 'ge0/2',
				status: 1,
				ip_address: '',
				hw_addr: '00-10-f3-8e-98-c2',
				negotiate: 0,
				speed: 1000,
				half: 0,
				max_speed: 1000,
				rx_pkt: '0',
				rx_pkt_total: '28855',
				send_pkt: '0',
				send_pkt_total: '593450',
				rx_byte: '0.000',
				rx_byte_total: '1732077',
				send_byte: '0.000',
				send_byte_total: '52712551',
				bw_usage: 0,
				interface_type: 0,
				row_total: 0,
				col_total: 0,
				pattern: 0,
				need_syn: 0,
				enable: 0,
				ha_backup: 0,
				sessionid: '',
			},
			{
				slot_param: [],
				grid_param: [],
				traffic_param: [],
				name: 'ge0/3',
				real_name: 'ge0/3',
				status: 0,
				ip_address: '',
				hw_addr: '00-10-f3-8e-98-c3',
				negotiate: 0,
				speed: 0,
				half: 0,
				max_speed: 0,
				rx_pkt: '0',
				rx_pkt_total: '0',
				send_pkt: '0',
				send_pkt_total: '0',
				rx_byte: '',
				rx_byte_total: '0',
				send_byte: '',
				send_byte_total: '0',
				bw_usage: 0,
				interface_type: 0,
				row_total: 0,
				col_total: 0,
				pattern: 0,
				need_syn: 0,
				enable: 0,
				ha_backup: 0,
				sessionid: '',
			},
			{
				slot_param: [],
				grid_param: [],
				traffic_param: [],
				name: 'ge0/4',
				real_name: 'ge0/4',
				status: 1,
				ip_address: '',
				hw_addr: '00-10-f3-8e-98-c4',
				negotiate: 0,
				speed: 1000,
				half: 0,
				max_speed: 1000,
				rx_pkt: '0',
				rx_pkt_total: '593450',
				send_pkt: '0',
				send_pkt_total: '28859',
				rx_byte: '0.000',
				rx_byte_total: '52723199',
				send_byte: '0.000',
				send_byte_total: '1732149',
				bw_usage: 0,
				interface_type: 0,
				row_total: 0,
				col_total: 0,
				pattern: 0,
				need_syn: 0,
				enable: 0,
				ha_backup: 0,
				sessionid: '',
			},
			{
				slot_param: [],
				grid_param: [],
				traffic_param: [],
				name: 'ge0/5',
				real_name: 'ge0/5',
				status: 0,
				ip_address: '',
				hw_addr: '00-10-f3-80-7c-d1',
				negotiate: 0,
				speed: 0,
				half: 0,
				max_speed: 0,
				rx_pkt: '0',
				rx_pkt_total: '0',
				send_pkt: '0',
				send_pkt_total: '0',
				rx_byte: '',
				rx_byte_total: '0',
				send_byte: '',
				send_byte_total: '0',
				bw_usage: 0,
				interface_type: 0,
				row_total: 0,
				col_total: 0,
				pattern: 0,
				need_syn: 0,
				enable: 0,
				ha_backup: 0,
				sessionid: '',
			},
			{
				slot_param: [],
				grid_param: [],
				traffic_param: [],
				name: 'ge0/6',
				real_name: 'ge0/6',
				status: 0,
				ip_address: '',
				hw_addr: '00-10-f3-80-7c-d2',
				negotiate: 0,
				speed: 0,
				half: 0,
				max_speed: 0,
				rx_pkt: '0',
				rx_pkt_total: '0',
				send_pkt: '0',
				send_pkt_total: '0',
				rx_byte: '',
				rx_byte_total: '0',
				send_byte: '',
				send_byte_total: '0',
				bw_usage: 0,
				interface_type: 0,
				row_total: 0,
				col_total: 0,
				pattern: 0,
				need_syn: 0,
				enable: 0,
				ha_backup: 0,
				sessionid: '',
			},
			{
				slot_param: [],
				grid_param: [],
				traffic_param: [],
				name: 'ge0/7',
				real_name: 'ge0/7',
				status: 0,
				ip_address: '',
				hw_addr: '00-10-f3-80-7c-d3',
				negotiate: 0,
				speed: 0,
				half: 0,
				max_speed: 0,
				rx_pkt: '0',
				rx_pkt_total: '0',
				send_pkt: '0',
				send_pkt_total: '0',
				rx_byte: '',
				rx_byte_total: '0',
				send_byte: '',
				send_byte_total: '0',
				bw_usage: 0,
				interface_type: 0,
				row_total: 0,
				col_total: 0,
				pattern: 0,
				need_syn: 0,
				enable: 0,
				ha_backup: 0,
				sessionid: '',
			},
			{
				slot_param: [],
				grid_param: [],
				traffic_param: [],
				name: 'ge0/8',
				real_name: 'ge0/8',
				status: 0,
				ip_address: '',
				hw_addr: '00-10-f3-80-7c-d4',
				negotiate: 0,
				speed: 0,
				half: 0,
				max_speed: 0,
				rx_pkt: '0',
				rx_pkt_total: '0',
				send_pkt: '0',
				send_pkt_total: '0',
				rx_byte: '',
				rx_byte_total: '0',
				send_byte: '',
				send_byte_total: '0',
				bw_usage: 0,
				interface_type: 0,
				row_total: 0,
				col_total: 0,
				pattern: 0,
				need_syn: 0,
				enable: 0,
				ha_backup: 0,
				sessionid: '',
			},
			{
				slot_param: [],
				grid_param: [],
				traffic_param: [],
				name: 'xge1/1',
				real_name: 'xge1/1',
				status: 0,
				ip_address: '',
				hw_addr: '80-61-5f-01-35-6c',
				negotiate: 0,
				speed: 0,
				half: 0,
				max_speed: 0,
				rx_pkt: '0',
				rx_pkt_total: '0',
				send_pkt: '0',
				send_pkt_total: '0',
				rx_byte: '',
				rx_byte_total: '0',
				send_byte: '',
				send_byte_total: '0',
				bw_usage: 0,
				interface_type: 0,
				row_total: 0,
				col_total: 0,
				pattern: 0,
				need_syn: 0,
				enable: 0,
				ha_backup: 0,
				sessionid: '',
			},
			{
				slot_param: [],
				grid_param: [],
				traffic_param: [],
				name: 'xge1/2',
				real_name: 'xge1/2',
				status: 0,
				ip_address: '',
				hw_addr: '80-61-5f-01-35-6d',
				negotiate: 0,
				speed: 0,
				half: 0,
				max_speed: 0,
				rx_pkt: '0',
				rx_pkt_total: '0',
				send_pkt: '0',
				send_pkt_total: '0',
				rx_byte: '',
				rx_byte_total: '0',
				send_byte: '',
				send_byte_total: '0',
				bw_usage: 0,
				interface_type: 0,
				row_total: 0,
				col_total: 0,
				pattern: 0,
				need_syn: 0,
				enable: 0,
				ha_backup: 0,
				sessionid: '',
			},
			{
				slot_param: [],
				grid_param: [],
				traffic_param: [],
				name: 'xge4/1',
				real_name: 'xge4/1',
				status: 0,
				ip_address: '',
				hw_addr: '00-90-0b-aa-c5-26',
				negotiate: 0,
				speed: 0,
				half: 0,
				max_speed: 0,
				rx_pkt: '0',
				rx_pkt_total: '0',
				send_pkt: '0',
				send_pkt_total: '0',
				rx_byte: '',
				rx_byte_total: '0',
				send_byte: '',
				send_byte_total: '0',
				bw_usage: 0,
				interface_type: 0,
				row_total: 0,
				col_total: 0,
				pattern: 0,
				need_syn: 0,
				enable: 0,
				ha_backup: 0,
				sessionid: '',
			},
			{
				slot_param: [],
				grid_param: [],
				traffic_param: [],
				name: 'xge4/2',
				real_name: 'xge4/2',
				status: 0,
				ip_address: '',
				hw_addr: '00-90-0b-aa-c5-27',
				negotiate: 0,
				speed: 0,
				half: 0,
				max_speed: 0,
				rx_pkt: '0',
				rx_pkt_total: '0',
				send_pkt: '0',
				send_pkt_total: '0',
				rx_byte: '',
				rx_byte_total: '0',
				send_byte: '',
				send_byte_total: '0',
				bw_usage: 0,
				interface_type: 0,
				row_total: 0,
				col_total: 0,
				pattern: 0,
				need_syn: 0,
				enable: 0,
				ha_backup: 0,
				sessionid: '',
			},
			{
				slot_param: [],
				grid_param: [],
				traffic_param: [],
				name: 'xge4/3',
				real_name: 'xge4/3',
				status: 0,
				ip_address: '',
				hw_addr: '00-90-0b-aa-c5-28',
				negotiate: 0,
				speed: 0,
				half: 0,
				max_speed: 0,
				rx_pkt: '0',
				rx_pkt_total: '0',
				send_pkt: '0',
				send_pkt_total: '0',
				rx_byte: '',
				rx_byte_total: '0',
				send_byte: '',
				send_byte_total: '0',
				bw_usage: 0,
				interface_type: 0,
				row_total: 0,
				col_total: 0,
				pattern: 0,
				need_syn: 0,
				enable: 0,
				ha_backup: 0,
				sessionid: '',
			},
			{
				slot_param: [],
				grid_param: [],
				traffic_param: [],
				name: 'xge4/4',
				real_name: 'xge4/4',
				status: 0,
				ip_address: '',
				hw_addr: '00-90-0b-aa-c5-29',
				negotiate: 0,
				speed: 0,
				half: 0,
				max_speed: 0,
				rx_pkt: '0',
				rx_pkt_total: '0',
				send_pkt: '0',
				send_pkt_total: '0',
				rx_byte: '',
				rx_byte_total: '0',
				send_byte: '',
				send_byte_total: '0',
				bw_usage: 0,
				interface_type: 0,
				row_total: 0,
				col_total: 0,
				pattern: 0,
				need_syn: 0,
				enable: 0,
				ha_backup: 0,
				sessionid: '',
			},
			{
				slot_param: [],
				grid_param: [],
				traffic_param: [],
				name: 'xge4/4',
				real_name: 'xge4/5',
				status: 0,
				ip_address: '',
				hw_addr: '00-90-0b-aa-c5-29',
				negotiate: 0,
				speed: 0,
				half: 0,
				max_speed: 0,
				rx_pkt: '0',
				rx_pkt_total: '0',
				send_pkt: '0',
				send_pkt_total: '0',
				rx_byte: '',
				rx_byte_total: '0',
				send_byte: '',
				send_byte_total: '0',
				bw_usage: 0,
				interface_type: 0,
				row_total: 0,
				col_total: 0,
				pattern: 0,
				need_syn: 0,
				enable: 0,
				ha_backup: 0,
				sessionid: '',
			},
			{
				slot_param: [],
				grid_param: [],
				traffic_param: [],
				name: 'xge4/4',
				real_name: 'xge4/6',
				status: 0,
				ip_address: '',
				hw_addr: '00-90-0b-aa-c5-29',
				negotiate: 0,
				speed: 0,
				half: 0,
				max_speed: 0,
				rx_pkt: '0',
				rx_pkt_total: '0',
				send_pkt: '0',
				send_pkt_total: '0',
				rx_byte: '',
				rx_byte_total: '0',
				send_byte: '',
				send_byte_total: '0',
				bw_usage: 0,
				interface_type: 0,
				row_total: 0,
				col_total: 0,
				pattern: 0,
				need_syn: 0,
				enable: 0,
				ha_backup: 0,
				sessionid: '',
			},
		],
	},
	itemList: {
		hostname: 'C236_107',
		product_name: '',
		produce_date: 'Dec  9 2022 18:04:25',
		serial_no: '2213801412129999',
		fw_version: 'V3.0R8.3B20221209(V3083)',
		dt_version: '2013-01-26',
		av_version: '',
		ips_version: '20221206',
		evil_url_version: '0',
		threat_version: '0',
		sys_time: 'Wed Jan 11 10:24:53 2023\n',
		uptime: 1121079,
		sessionid: '',
	},
	layoutList: {
		slot_param: [
			{
				slot_id: 0,
				row: 1,
				col: 0,
			},
			{
				slot_id: 1,
				row: 1,
				col: 2,
			},
			{
				slot_id: 2,
				row: 1,
				col: 3,
			},
			{
				slot_id: 3,
				row: 0,
				col: 0,
			},
			{
				slot_id: 4,
				row: 0,
				col: 1,
			},
			{
				slot_id: 5,
				row: 0,
				col: 2,
			},
			{
				slot_id: 6,
				row: 0,
				col: 3,
			},
		],
		grid_param: [
			{
				slot_id: 0,
				row: 1,
				col: 0,
				real_name: 'ge0/1',
				media_type: 1,
			},
			{
				slot_id: 0,
				row: 1,
				col: 1,
				real_name: 'ge0/2',
				media_type: 1,
			},
			{
				slot_id: 0,
				row: 1,
				col: 2,
				real_name: 'ge0/3',
				media_type: 1,
			},
			{
				slot_id: 0,
				row: 1,
				col: 3,
				real_name: 'ge0/4',
				media_type: 1,
			},
			{
				slot_id: 0,
				row: 0,
				col: 0,
				real_name: 'ge0/5',
				media_type: 2,
			},
			{
				slot_id: 0,
				row: 0,
				col: 1,
				real_name: 'ge0/6',
				media_type: 2,
			},
			{
				slot_id: 0,
				row: 0,
				col: 2,
				real_name: 'ge0/7',
				media_type: 2,
			},
			{
				slot_id: 0,
				row: 0,
				col: 3,
				real_name: 'ge0/8',
				media_type: 2,
			},
			{
				slot_id: 1,
				row: 1,
				col: 0,
				real_name: 'xge1/1',
				media_type: 2,
			},
			{
				slot_id: 1,
				row: 1,
				col: 1,
				real_name: 'xge1/2',
				media_type: 2,
			},
			{
				slot_id: 4,
				row: 1,
				col: 0,
				real_name: 'xge4/1',
				media_type: 2,
			},
			{
				slot_id: 4,
				row: 1,
				col: 1,
				real_name: 'xge4/2',
				media_type: 2,
			},
			{
				slot_id: 4,
				row: 1,
				col: 2,
				real_name: 'xge4/3',
				media_type: 2,
			},
			{
				slot_id: 4,
				row: 1,
				col: 3,
				real_name: 'xge4/4',
				media_type: 2,
			},
			{
				slot_id: 0,
				row: 2,
				col: 0,
				real_name: 'xge4/5',
				media_type: 2,
			},
			{
				slot_id: 0,
				row: 2,
				col: 1,
				real_name: 'xge4/6',
				media_type: 2,
			},
		],
		traffic_param: [],
		name: '',
		real_name: '',
		status: 0,
		ip_address: '',
		hw_addr: '',
		negotiate: 0,
		speed: 0,
		half: 0,
		max_speed: 0,
		rx_pkt: '0',
		rx_pkt_total: '0',
		send_pkt: '0',
		send_pkt_total: '0',
		rx_byte: '',
		rx_byte_total: '0',
		send_byte: '',
		send_byte_total: '0',
		bw_usage: 0,
		interface_type: 0,
		row_total: 2,
		col_total: 4,
		pattern: 0,
		need_syn: 0,
		enable: 0,
		ha_backup: 0,
		sessionid: '',
	},
	oneKeySlotConfig: {
		type: 0,
		slot: -1,
		sessionid: '',
	},
	deploymode: '1',
}
